language: r
warnings_are_errors: false
r_packages:
  - usethis
before_install: 
  - echo 'install.packages("usethis")' | R --no-save
  - R --no-save < data-raw/build_data.R
r:
  - oldrel
  - release
  
