language: r
warnings_are_errors: false
r_packages:
  - usethis
before_install: 
  - echo 'install.packages("usethis")' | R --no-save
  - R --no-save < data-raw/build_data.R
r:
  - oldrel
  - release
script:
  - travis_wait 60 R CMD build ${R_BUILD_ARGS} .
  - rm -f travis_wait*.log
  - travis_wait 60 R CMD check ${R_CHECK_ARGS} *.tar.gz; CHECK_RET=$? ;
  - rm -f travis_wait*.log
  - if [[ $CHECK_RET -ne 0 ]];
    then
      echo "R CMD check failed";
      check_fail;
      dump_logs;
      check_warnings ;
      travis_terminate 1;
    fi


